### ISSUE TITLE
got an error `SyntaxError: Cannot use import statement outside a module`

### ISSUE THREAD

**Issue by darrylsepeda** [tanisha-verma/lottie-web-react#3]
```
SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Module._compile (/Users/x/Documents/Github/eweddings/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.newLoader [as .js] (/Users/x/Documents/Github/eweddings/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.lottieWebReact (webpack:/external "axios":1:1)
    at __webpack_require__ (webpack:///webpack/bootstrap:27:1)
    at Module.componentsFeaturesJs (/Users/x/Documents/Github/eweddings/build/next/server/static/development/pages/_error.js:323:2742)
    at __webpack_require__ (webpack:///webpack/bootstrap:27:1)
    at Module.componentsIndexJs (webpack:///components/index.js:1:1)
    at __webpack_require__ (webpack:///webpack/bootstrap:27:1)
    at Module.pages_errorJs (/Users/x/Documents/Github/eweddings/build/next/server/static/development/pages/_error.js:457:920)
    at __webpack_require__ (webpack:///webpack/bootstrap:27:1)
    at Object._ (/Users/x/Documents/Github/eweddings/build/next/server/static/development/pages/_error.js:517:135)
    at __webpack_require__ (webpack:///webpack/bootstrap:27:1)
    at module.exports.../next-server/lib/router-context (webpack:///webpack/bootstrap:122:1)
    at Object.<anonymous> (/Users/x/Documents/Github/eweddings/build/next/server/static/development/pages/_error.js:30:70)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Module._compile (/Users/x/Documents/Github/eweddings/node_modules/pirates/lib/index.js:99:24)
/Users/x/Dcuments/Github/eweddings/node_modules/lottie-web-react/dist/index.js:1
import React, { useRef, useEffect, useState, useCallback, useReducer } from 'react';
^^^^^^
```

I have implemented exactly same by importing `lottie-web-react` and call <Lottie /> component, but when I open the page, the error above shows up.

**Comment by vexxvakan** [comment]
Have you ever figured that out? Stuck on the same problem here.....

**Comment by KeitelDOG** [comment]
You didn't specified any detail of your environment or how to reproduce the issue.
I'm using:

- React Native 0.68.1
- React 17.0.2
- React Native Web 0.17.7
- Next JS 12.1.6 with custom configuration
- Node 16.13.0

Everything works great. But when I install Lottie React Native, compiling with NextJS for web, and just importing it (not even rendering it yet), it gave me same error.

**Comment by KeitelDOG** [comment]
**EDIT: I just realized that this was the React version and not React Native one. Cause now I need the React Version for Next. I will let you know if it works for me.**

I found the Solution for Next JS in my case. It was because of next config didn't transpiled the module. The normal config codes filtered all react native module in `package.json` to transpile modules starting with `react-native` and react navigation modules:

```js
let modulesToTranspile = [
  ...Object.keys(packageJson.dependencies).filter(dep => {
    return dep.startsWith('react-native') || dep.startsWith('@react-native');
  }),
];

const modulesList = [
  '@react-navigation/drawer',
  '@react-navigation/native',
  '@react-navigation/stack',
  'lottie-react-native',
];
```

and because `lottie-react-native` was the only one which didn't start with `react-native`, I added it manually.
